- name: Proxmox stuff
  hosts: proxmox
  tasks:
    - set_fact:
        hostname: "windows-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    - proxmox_kvm:
        api_user    : root@pam
        api_password: Password
        api_host    : 100.124.109.92
        clone       : windowstemplate   # The VM source
        name        : "{{ yeppers }}"  # The target VM name
        node        : main
        storage     : vms-ssd
        format      : qcow2
        timeout     : 500  # Note: The task can take a while. Adapt
    - name: Add host to group 'just_created'
    add_host:
      name: '{{ hostname }}'
      groups: just_created