name: Feature Branch Creation

on:
  issues:
    types: [ labeled ]


jobs:
  create-feature-branch:
    if: contains(github.event.issue.labels.*.name, 'feature')
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new branch based on the request
        run: |
          git checkout Dev
          git checkout -b "feature_branch-${GITHUB_RUN_NUMBER}"
          git push --set-upstream origin "feature_branch-${GITHUB_RUN_NUMBER}"
